#ifndef RETRACE_RUNTIME_PROTOCOL_H
#define RETRACE_RUNTIME_PROTOCOL_H

#include <stdint.h>

#define RETRACE_RUNTIME_EVENT_FD_ENV "RETRACE_RUNTIME_EVENT_FD"

#define RETRACE_RUNTIME_PROTOCOL_MAGIC_0 ((uint8_t)'R')
#define RETRACE_RUNTIME_PROTOCOL_MAGIC_1 ((uint8_t)'T')
#define RETRACE_RUNTIME_PROTOCOL_MAGIC_2 ((uint8_t)'R')
#define RETRACE_RUNTIME_PROTOCOL_MAGIC_3 ((uint8_t)'N')

#define RETRACE_RUNTIME_PROTOCOL_MAJOR UINT16_C(1)
#define RETRACE_RUNTIME_PROTOCOL_MINOR UINT16_C(0)

#define RETRACE_RUNTIME_FRAME_HEADER_SIZE UINT32_C(16)
#define RETRACE_RUNTIME_FRAME_MAX_PAYLOAD_SIZE (UINT32_C(64) * UINT32_C(1024))

#define RETRACE_RUNTIME_FRAME_MAGIC_OFFSET UINT32_C(0)
#define RETRACE_RUNTIME_FRAME_MAJOR_OFFSET UINT32_C(4)
#define RETRACE_RUNTIME_FRAME_MINOR_OFFSET UINT32_C(6)
#define RETRACE_RUNTIME_FRAME_TYPE_OFFSET UINT32_C(8)
#define RETRACE_RUNTIME_FRAME_FLAGS_OFFSET UINT32_C(10)
#define RETRACE_RUNTIME_FRAME_PAYLOAD_SIZE_OFFSET UINT32_C(12)

enum retrace_runtime_message_type {
  RETRACE_RUNTIME_MESSAGE_HANDSHAKE = 1,
};

#endif
